// Demo-data så Dashboard ikke står tomt ved første åbning.
// Indlæses kun hvis brugeren ikke allerede har data i localStorage.

import type { HistoricalOffer } from "./types";

export const sampleHistorical: HistoricalOffer[] = [
  {
    projectName: "Aalborg Lager A",
    areaType: "Lager",
    luminaireCount: 120,
    controlType: "MasterConnect",
    luxLevel: 300,
    kelvin: 4000,
    annualBurnHours: 3500,
    electricityPrice: 2.1,
    estimatedPrice: 450000,
    actualPrice: 472000,
    status: "Vundet",
  },
  {
    projectName: "Kontorhus Vest",
    areaType: "Kontor",
    luminaireCount: 85,
    controlType: "DALI",
    luxLevel: 500,
    kelvin: 4000,
    annualBurnHours: 2400,
    electricityPrice: 2.3,
    estimatedPrice: 320000,
    actualPrice: 305000,
    status: "Vundet",
  },
  {
    projectName: "Sportshal Nord",
    areaType: "Sportshal",
    luminaireCount: 64,
    controlType: "Trådløs styring",
    luxLevel: 500,
    kelvin: 5000,
    annualBurnHours: 2800,
    electricityPrice: 2.0,
    estimatedPrice: 280000,
    actualPrice: 312000,
    status: "Vundet",
  },
  {
    projectName: "Produktion Esbjerg",
    areaType: "Produktion",
    luminaireCount: 210,
    controlType: "MasterConnect",
    luxLevel: 300,
    kelvin: 4000,
    annualBurnHours: 4200,
    electricityPrice: 1.9,
    estimatedPrice: 820000,
    actualPrice: 865000,
    status: "Vundet",
  },
  {
    projectName: "Detail Aarhus",
    areaType: "Butik",
    luminaireCount: 40,
    controlType: "Dagslysstyring",
    luxLevel: 500,
    kelvin: 3000,
    annualBurnHours: 3000,
    electricityPrice: 2.5,
    estimatedPrice: 180000,
    actualPrice: 175000,
    status: "Tabt",
  },
];
