// Demo-data så Dashboard ikke står tomt ved første åbning.
// Indlæses kun hvis brugeren ikke allerede har data i localStorage.
// Områder og styringsformer matcher v1-fokus: Kontor og Industri.

import type { HistoricalOffer } from "./types";

export const sampleHistorical: HistoricalOffer[] = [
  {
    projectName: "Industrihal Aalborg",
    areaType: "Industri",
    luminaireCount: 120,
    controlType: "MasterConnect",
    luxLevel: 300,
    kelvin: 4000,
    annualBurnHours: 3500,
    electricityPrice: 2.1,
    estimatedPrice: 450000,
    actualPrice: 472000,
    status: "Vundet",
  },
  {
    projectName: "Kontorhus Vest",
    areaType: "Kontor",
    luminaireCount: 85,
    controlType: "DALI-2",
    luxLevel: 500,
    kelvin: 4000,
    annualBurnHours: 2400,
    electricityPrice: 2.3,
    estimatedPrice: 320000,
    actualPrice: 305000,
    status: "Vundet",
  },
  {
    projectName: "Produktion Esbjerg",
    areaType: "Industri",
    luminaireCount: 210,
    controlType: "MasterConnect",
    luxLevel: 300,
    kelvin: 4000,
    annualBurnHours: 4200,
    electricityPrice: 1.9,
    estimatedPrice: 820000,
    actualPrice: 865000,
    status: "Vundet",
  },
  {
    projectName: "Domicil Aarhus",
    areaType: "Kontor",
    luminaireCount: 140,
    controlType: "Casambi",
    luxLevel: 500,
    kelvin: 4000,
    annualBurnHours: 2600,
    electricityPrice: 2.4,
    estimatedPrice: 510000,
    actualPrice: 498000,
    status: "Vundet",
  },
  {
    projectName: "Værksted Kolding",
    areaType: "Industri",
    luminaireCount: 60,
    controlType: "Bevægelsessensor",
    luxLevel: 300,
    kelvin: 5000,
    annualBurnHours: 3000,
    electricityPrice: 2.2,
    estimatedPrice: 210000,
    actualPrice: 232000,
    status: "Tabt",
  },
];
