/*
 * green light · Dokumenttjek — standardregler ("tjeklisten")
 *
 * Hver regel beskriver én ensretning: find → erstat.
 * Reglerne kan redigeres, slås til/fra, slettes og suppleres direkte i
 * programmet (fanen "Tjeklisten"), og gemmes derefter i browserens
 * localStorage. Denne fil er kun UDGANGSPUNKTET — den indlæses første
 * gang, og når man vælger "Gendan standardregler".
 *
 * Regel-format:
 *   id        stabil nøgle (bruges i ændringsrapporten)
 *   category  gruppering i UI'et
 *   find      søgetekst eller regulært udtryk
 *   replace   erstatningstekst ($1, $2 … ved regex)
 *   note      forklaring der vises i UI'et
 *   regex     true = "find" tolkes som regulært udtryk
 *   matchCase true = kun præcis samme store/små bogstaver matches
 *   wholeWord true = matcher kun hele ord (dansk-sikkert, forstår æøå)
 *   afterDigit true = må også stå klistret lige efter et tal (enheder:
 *             "2400m2", "1000kr")
 *   smartCase true = stort begyndelsesbogstav i matchet bevares
 *             automatisk i erstatningen (fx "Ihht." → "Iht.")
 *   enabled   false = reglen står klar, men er slået fra som standard
 *
 * RÆKKEFØLGEN ER BEVIDST: typografi-reglerne står først, så sjusk som
 * "kr ." og "Green  light" er normaliseret, FØR punktum- og navneregler
 * kører (ellers kunne resultatet blive "kr.." m.m.).
 *
 * Flere regler bruger lookarounds som (?<!/) og (?![.\-/]) for aldrig at
 * ramme webadresser, e-mailadresser, varenumre og typekoder (fx
 * green-light.dk, no-reply@email…, CO2-5566, IHT-2000, /nr/123).
 */
window.GL_DEFAULT_RULES = [
  // ── Typografi & mellemrum (kører først – se ovenfor) ────────────────
  {
    id: "typo-dobbelt-mellemrum",
    category: "Typografi & mellemrum",
    find: "(?<! ) {2,3}(?! )",
    replace: " ",
    note: "2\u20133 mellemrum rettes til \u00e9t. L\u00e6ngere r\u00e6kker (4+) betragtes som bevidst opstilling/spalter og r\u00f8res ikke.",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: true,
  },
  {
    id: "typo-mellemrum-tegn",
    category: "Typografi & mellemrum",
    find: " +([,.;:!?])",
    replace: "$1",
    note: "Mellemrum f\u00f8r tegns\u00e6tning fjernes (\u00bbpris :\u00ab \u2192 \u00bbpris:\u00ab).",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: true,
  },
  {
    id: "typo-tankestreg",
    category: "Typografi & mellemrum",
    find: "(\\d) ?- ?(\\d)",
    replace: "$1\u2013$2",
    note: "Tankestreg i intervaller (10\u201320). Sl\u00e5et fra som standard, da bindestreg ogs\u00e5 bruges i varenumre og telefonnumre.",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: false,
  },
  {
    id: "typo-citationstegn",
    category: "Typografi & mellemrum",
    find: "\"([^\"\\n]{1,120})\"",
    replace: "\u201d$1\u201d",
    note: "Lige anf\u00f8rselstegn \"..\" \u2192 danske \u201d..\u201d. Sl\u00e5 til, hvis det er jeres standard (obs: rammer ogs\u00e5 tommer-angivelser som 19\").",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: false,
  },

  // ── Firmanavn ────────────────────────────────────────────────────────
  {
    id: "brand-green-light",
    category: "Firmanavn",
    find: "(?<![@./-])green[\\s-]?light(?![-.@/][\\p{L}\\p{N}])",
    replace: "green light",
    note: "Firmanavnet skrives \u00bbgreen light\u00ab \u2013 med sm\u00e5t og i to ord. Webadresser, e-mails og domæner (green-light.dk, sharepoint-links m.m.) r\u00f8res ikke.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },

  // ── Stavning & forkortelser ─────────────────────────────────────────
  {
    id: "stav-ordrebekraeftelse",
    category: "Stavning & forkortelser",
    find: "ordrebekr\u00e6ftigelse",
    replace: "ordrebekr\u00e6ftelse",
    note: "Hyppig stavefejl \u2013 der er intet \u00bbig\u00ab i ordrebekr\u00e6ftelse. Rammer ogs\u00e5 b\u00f8jninger (\u2026sen, \u2026ser).",
    regex: false,
    matchCase: false,
    wholeWord: false,
    smartCase: true,
    enabled: true,
  },
  {
    id: "stav-tilbuddet",
    category: "Stavning & forkortelser",
    find: "tilbudet",
    replace: "tilbuddet",
    note: "Kun \u00bbtilbuddet\u00ab er korrekt (Retskrivningsordbogen 2012).",
    regex: false,
    matchCase: false,
    wholeWord: false,
    smartCase: true,
    enabled: true,
  },
  {
    id: "stav-tilbuddene",
    category: "Stavning & forkortelser",
    find: "tilbudene",
    replace: "tilbuddene",
    note: "Samme regel i flertal.",
    regex: false,
    matchCase: false,
    wholeWord: false,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-iht",
    category: "Stavning & forkortelser",
    find: "ihht\\.?",
    replace: "iht.",
    note: "\u00bbI henhold til\u00ab forkortes iht. \u2013 ikke ihht.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-iht-punktum",
    category: "Stavning & forkortelser",
    find: "(?<!/)iht(?![.\\-/])",
    replace: "iht.",
    note: "Manglende punktum efter iht. (typekoder som IHT-2000 og webadresser r\u00f8res ikke).",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-jf",
    category: "Stavning & forkortelser",
    find: "jvf\\.?",
    replace: "jf.",
    note: "\u00bbJ\u00e6vnf\u00f8r\u00ab forkortes jf. \u2013 ikke jvf.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-ekskl",
    category: "Stavning & forkortelser",
    find: "excl\\.?",
    replace: "ekskl.",
    note: "Dansk forkortelse: ekskl. \u2013 ikke excl.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-inkl",
    category: "Stavning & forkortelser",
    find: "incl\\.?",
    replace: "inkl.",
    note: "Dansk forkortelse: inkl. \u2013 ikke incl.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-ekskl-punktum",
    category: "Stavning & forkortelser",
    find: "ekskl(?![.\\-/])",
    replace: "ekskl.",
    note: "Manglende punktum efter ekskl.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-inkl-punktum",
    category: "Stavning & forkortelser",
    find: "inkl(?![.\\-/])",
    replace: "inkl.",
    note: "Manglende punktum efter inkl.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-feks",
    category: "Stavning & forkortelser",
    find: "f\\.eks(?!\\.)",
    replace: "f.eks.",
    note: "Manglende punktum efter f.eks.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-bla",
    category: "Stavning & forkortelser",
    find: "bl\\.a(?!\\.)",
    replace: "bl.a.",
    note: "Manglende punktum efter bl.a.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-dvs",
    category: "Stavning & forkortelser",
    find: "d\\.v\\.s\\.?|dvs(?![.\\-/])",
    replace: "dvs.",
    note: "\u00bbDet vil sige\u00ab forkortes dvs. (uden ekstra punktummer).",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-vedr",
    category: "Stavning & forkortelser",
    find: "(?<!/)vedr(?![.\\-/])",
    replace: "vedr.",
    note: "Manglende punktum efter vedr.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-att",
    category: "Stavning & forkortelser",
    find: "(?<!/)att(?![.\\-/])",
    replace: "att.",
    note: "Manglende punktum efter att. (typekoder som ATT-40 r\u00f8res ikke).",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-nr",
    category: "Stavning & forkortelser",
    find: "(?<!/)nr(?![.\\-/])",
    replace: "nr.",
    note: "Manglende punktum efter nr. (webadresser med /nr/ r\u00f8res ikke).",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "stav-email",
    category: "Stavning & forkortelser",
    find: "(?<![.@/])email(?!\\.\\p{L}|@)",
    replace: "e-mail",
    note: "P\u00e5 dansk hedder det e-mail (med bindestreg). E-mailadresser og webadresser (fx no-reply@email\u2026) r\u00f8res ikke.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "stav-aconto",
    category: "Stavning & forkortelser",
    find: "a['\u2019`]?\\s?conto",
    replace: "a conto",
    note: "V\u00e6lg \u00e9n fast form (Retskrivningsordbogen: \u00bba conto\u00ab i to ord). Sl\u00e5 til, n\u00e5r I har besluttet jeres standard.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: false,
  },

  // ── Enheder & tal ───────────────────────────────────────────────────
  {
    id: "enhed-kwh-tal",
    category: "Enheder & tal",
    find: "(\\d[\\d.,]*)[ \\u00A0]?kwh(?![-\u2013])",
    replace: "$1 kWh",
    note: "Kilowatt-timer efter et tal skrives \u00bb45.000 kWh\u00ab \u2013 ogs\u00e5 n\u00e5r tallet st\u00e5r klistret p\u00e5 (45000kwh). Koder som EV-KWH-10 r\u00f8res ikke.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-kwh-ord",
    category: "Enheder & tal",
    find: "kwh(?![-\u2013])",
    replace: "kWh",
    note: "kwh uden tal foran (fx \u00bbpris pr. kwh\u00ab) rettes ogs\u00e5. Kun sm\u00e5 bogstaver \u2013 s\u00e5 koder i versaler r\u00f8res ikke.",
    regex: true,
    matchCase: true,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-co2",
    category: "Enheder & tal",
    find: "(?<![\\p{L}\\p{N}][-\u2013])co2(?![-\u2013]\\d)",
    replace: "CO\u2082",
    note: "CO\u2082 med s\u00e6nket 2-tal. Varenumre og koder (CO2-5566, GS-CO2) r\u00f8res ikke \u2013 \u00bbCO2-besparelse\u00ab rettes stadig.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-m2-tal",
    category: "Enheder & tal",
    find: "(\\d[\\d.,]*)[ \\u00A0]?m2(?![-\u2013])",
    replace: "$1 m\u00b2",
    note: "Kvadratmeter efter et tal skrives \u00bb2.400 m\u00b2\u00ab \u2013 ogs\u00e5 n\u00e5r tallet st\u00e5r klistret p\u00e5 (2400m2). Typekoder som M2-25 r\u00f8res ikke.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-m2-ord",
    category: "Enheder & tal",
    find: "m2(?![-\u2013])",
    replace: "m\u00b2",
    note: "m2 uden tal foran (fx \u00bbpris pr. m2\u00ab) rettes ogs\u00e5. Kun sm\u00e5 bogstaver \u2013 s\u00e5 typekoder i versaler r\u00f8res ikke.",
    regex: true,
    matchCase: true,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-kvm-midt",
    category: "Enheder & tal",
    find: "kvm\\.(?=\\s*[a-z\u00e6\u00f8\u00e50-9])",
    replace: "m\u00b2",
    note: "kvm. midt i en s\u00e6tning \u2192 m\u00b2 (forkortelsespunktummet fjernes).",
    regex: true,
    matchCase: true,
    wholeWord: true,
    afterDigit: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-kvm",
    category: "Enheder & tal",
    find: "kvm(?![-\u2013])",
    replace: "m\u00b2",
    note: "Ensret kvm til m\u00b2. Sidst i en s\u00e6tning bevares punktummet (\u00bb250 kvm.\u00ab \u2192 \u00bb250 m\u00b2.\u00ab), og KVM-koder med bindestreg r\u00f8res ikke.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    afterDigit: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-lmw",
    category: "Enheder & tal",
    find: "lm/w",
    replace: "lm/W",
    note: "Lumen pr. watt skrives lm/W.",
    regex: false,
    matchCase: false,
    wholeWord: true,
    afterDigit: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-kr",
    category: "Enheder & tal",
    find: "kr(?![.\\-])",
    replace: "kr.",
    note: "Manglende punktum efter kr. \u2013 ogs\u00e5 n\u00e5r bel\u00f8bet st\u00e5r klistret p\u00e5 (1000kr).",
    regex: true,
    matchCase: false,
    wholeWord: true,
    afterDigit: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "enhed-dkk",
    category: "Enheder & tal",
    find: "dkk(?![.\\-])",
    replace: "kr.",
    note: "Ensret DKK til kr. \u2013 sl\u00e5 til, hvis kr. er jeres standard.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    afterDigit: true,
    smartCase: false,
    enabled: false,
  },
  {
    id: "enhed-procent",
    category: "Enheder & tal",
    find: "(\\d)%",
    replace: "$1 %",
    note: "Retskrivningsordbogen anbefaler mellemrum f\u00f8r %-tegnet (50 %). Sl\u00e5 til, hvis det er jeres standard.",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: false,
  },

  // ── Formuleringer ───────────────────────────────────────────────────
  {
    id: "form-mvh",
    category: "Formuleringer",
    find: "[Mm]vh\\.?",
    replace: "Med venlig hilsen",
    note: "I tilbud og ordrebekr\u00e6ftelser skrives hilsenen helt ud. Initialer i versaler (\u00bbVor ref.: MVH\u00ab) r\u00f8res ikke.",
    regex: true,
    matchCase: true,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "form-venlig-hilsen",
    category: "Formuleringer",
    find: "Venlig hilsen",
    replace: "Med venlig hilsen",
    note: "Ensret til \u00e9n fast afslutningshilsen. Sl\u00e5 til, hvis \u00bbMed venlig hilsen\u00ab er jeres standard.",
    regex: false,
    matchCase: true,
    wholeWord: true,
    smartCase: false,
    enabled: false,
  },
];
