/*
 * green light · Dokumenttjek — standardregler ("tjeklisten")
 *
 * Hver regel beskriver én ensretning: find → erstat.
 * Reglerne kan redigeres, slås til/fra, slettes og suppleres direkte i
 * programmet (fanen "Tjeklisten"), og gemmes derefter i browserens
 * localStorage. Denne fil er kun UDGANGSPUNKTET — den indlæses første
 * gang, og når man vælger "Gendan standardregler".
 *
 * Regel-format:
 *   id        stabil nøgle (bruges i ændringsrapporten)
 *   category  gruppering i UI'et
 *   find      søgetekst eller regulært udtryk
 *   replace   erstatningstekst ($1, $2 … ved regex)
 *   note      forklaring der vises i UI'et
 *   regex     true = "find" tolkes som regulært udtryk
 *   matchCase true = kun præcis samme store/små bogstaver matches
 *   wholeWord true = matcher kun hele ord (dansk-sikkert, forstår æøå)
 *   smartCase true = stort begyndelsesbogstav i matchet bevares
 *             automatisk i erstatningen (fx "Ihht." → "Iht.")
 *   enabled   false = reglen står klar, men er slået fra som standard
 */
window.GL_DEFAULT_RULES = [
  // ── Firmanavn ────────────────────────────────────────────────────────
  {
    id: "brand-green-light",
    category: "Firmanavn",
    find: "green[\\s-]?light(?!\\.dk)",
    replace: "green light",
    note: "Firmanavnet skrives \u00bbgreen light\u00ab \u2013 med sm\u00e5t og i to ord. Webadresser og e-mails (green-light.dk) r\u00f8res ikke.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },

  // ── Stavning & forkortelser ─────────────────────────────────────────
  {
    id: "stav-ordrebekraeftelse",
    category: "Stavning & forkortelser",
    find: "ordrebekr\u00e6ftigelse",
    replace: "ordrebekr\u00e6ftelse",
    note: "Hyppig stavefejl \u2013 der er intet \u00bbig\u00ab i ordrebekr\u00e6ftelse. Rammer ogs\u00e5 b\u00f8jninger (\u2026sen, \u2026ser).",
    regex: false,
    matchCase: false,
    wholeWord: false,
    smartCase: true,
    enabled: true,
  },
  {
    id: "stav-tilbuddet",
    category: "Stavning & forkortelser",
    find: "tilbudet",
    replace: "tilbuddet",
    note: "Kun \u00bbtilbuddet\u00ab er korrekt (Retskrivningsordbogen 2012).",
    regex: false,
    matchCase: false,
    wholeWord: false,
    smartCase: true,
    enabled: true,
  },
  {
    id: "stav-tilbuddene",
    category: "Stavning & forkortelser",
    find: "tilbudene",
    replace: "tilbuddene",
    note: "Samme regel i flertal.",
    regex: false,
    matchCase: false,
    wholeWord: false,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-iht",
    category: "Stavning & forkortelser",
    find: "ihht\\.?",
    replace: "iht.",
    note: "\u00bbI henhold til\u00ab forkortes iht. \u2013 ikke ihht.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-iht-punktum",
    category: "Stavning & forkortelser",
    find: "iht(?!\\.)",
    replace: "iht.",
    note: "Manglende punktum efter iht.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-jf",
    category: "Stavning & forkortelser",
    find: "jvf\\.?",
    replace: "jf.",
    note: "\u00bbJ\u00e6vnf\u00f8r\u00ab forkortes jf. \u2013 ikke jvf.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-ekskl",
    category: "Stavning & forkortelser",
    find: "excl\\.?",
    replace: "ekskl.",
    note: "Dansk forkortelse: ekskl. \u2013 ikke excl.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-inkl",
    category: "Stavning & forkortelser",
    find: "incl\\.?",
    replace: "inkl.",
    note: "Dansk forkortelse: inkl. \u2013 ikke incl.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-ekskl-punktum",
    category: "Stavning & forkortelser",
    find: "ekskl(?!\\.)",
    replace: "ekskl.",
    note: "Manglende punktum efter ekskl.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-inkl-punktum",
    category: "Stavning & forkortelser",
    find: "inkl(?!\\.)",
    replace: "inkl.",
    note: "Manglende punktum efter inkl.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-feks",
    category: "Stavning & forkortelser",
    find: "f\\.eks(?!\\.)",
    replace: "f.eks.",
    note: "Manglende punktum efter f.eks.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-bla",
    category: "Stavning & forkortelser",
    find: "bl\\.a(?!\\.)",
    replace: "bl.a.",
    note: "Manglende punktum efter bl.a.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-dvs",
    category: "Stavning & forkortelser",
    find: "d\\.v\\.s\\.?|dvs(?!\\.)",
    replace: "dvs.",
    note: "\u00bbDet vil sige\u00ab forkortes dvs. (uden ekstra punktummer).",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-vedr",
    category: "Stavning & forkortelser",
    find: "vedr(?!\\.)",
    replace: "vedr.",
    note: "Manglende punktum efter vedr.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-att",
    category: "Stavning & forkortelser",
    find: "att(?!\\.)",
    replace: "att.",
    note: "Manglende punktum efter att.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "fork-nr",
    category: "Stavning & forkortelser",
    find: "nr(?!\\.)",
    replace: "nr.",
    note: "Manglende punktum efter nr.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "stav-email",
    category: "Stavning & forkortelser",
    find: "email",
    replace: "e-mail",
    note: "P\u00e5 dansk hedder det e-mail (med bindestreg).",
    regex: false,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "stav-aconto",
    category: "Stavning & forkortelser",
    find: "a['\u2019`]?\\s?conto",
    replace: "a conto",
    note: "V\u00e6lg \u00e9n fast form (Retskrivningsordbogen: \u00bba conto\u00ab i to ord). Sl\u00e5 til, n\u00e5r I har besluttet jeres standard.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: false,
  },

  // ── Enheder & tal ───────────────────────────────────────────────────
  {
    id: "enhed-kwh",
    category: "Enheder & tal",
    find: "kwh",
    replace: "kWh",
    note: "Kilowatt-timer skrives kWh.",
    regex: false,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-co2",
    category: "Enheder & tal",
    find: "co2",
    replace: "CO\u2082",
    note: "CO\u2082 med s\u00e6nket 2-tal.",
    regex: false,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-m2",
    category: "Enheder & tal",
    find: "m2",
    replace: "m\u00b2",
    note: "Kvadratmeter skrives m\u00b2.",
    regex: false,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-kvm",
    category: "Enheder & tal",
    find: "kvm\\.?",
    replace: "m\u00b2",
    note: "Ensret kvm/kvm. til m\u00b2.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-lmw",
    category: "Enheder & tal",
    find: "lm/w",
    replace: "lm/W",
    note: "Lumen pr. watt skrives lm/W.",
    regex: false,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "enhed-kr",
    category: "Enheder & tal",
    find: "kr(?!\\.)",
    replace: "kr.",
    note: "Manglende punktum efter kr.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: true,
    enabled: true,
  },
  {
    id: "enhed-dkk",
    category: "Enheder & tal",
    find: "dkk",
    replace: "kr.",
    note: "Ensret DKK til kr. \u2013 sl\u00e5 til, hvis kr. er jeres standard.",
    regex: false,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: false,
  },
  {
    id: "enhed-procent",
    category: "Enheder & tal",
    find: "(\\d)%",
    replace: "$1 %",
    note: "Retskrivningsordbogen anbefaler mellemrum f\u00f8r %-tegnet (50 %). Sl\u00e5 til, hvis det er jeres standard.",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: false,
  },

  // ── Typografi & mellemrum ───────────────────────────────────────────
  {
    id: "typo-dobbelt-mellemrum",
    category: "Typografi & mellemrum",
    find: " {2,}",
    replace: " ",
    note: "Dobbelte (og flere) mellemrum rettes til \u00e9t.",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: true,
  },
  {
    id: "typo-mellemrum-tegn",
    category: "Typografi & mellemrum",
    find: " +([,.;:!?])",
    replace: "$1",
    note: "Mellemrum f\u00f8r tegns\u00e6tning fjernes (\u00bbpris :\u00ab \u2192 \u00bbpris:\u00ab).",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: true,
  },
  {
    id: "typo-tankestreg",
    category: "Typografi & mellemrum",
    find: "(\\d) ?- ?(\\d)",
    replace: "$1\u2013$2",
    note: "Tankestreg i intervaller (10\u201320). Sl\u00e5et fra som standard, da bindestreg ogs\u00e5 bruges i varenumre og telefonnumre.",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: false,
  },
  {
    id: "typo-citationstegn",
    category: "Typografi & mellemrum",
    find: "\"([^\"\\n]{1,120})\"",
    replace: "\u201d$1\u201d",
    note: "Lige anf\u00f8rselstegn \"..\" \u2192 danske \u201d..\u201d. Sl\u00e5 til, hvis det er jeres standard.",
    regex: true,
    matchCase: false,
    wholeWord: false,
    smartCase: false,
    enabled: false,
  },

  // ── Formuleringer ───────────────────────────────────────────────────
  {
    id: "form-mvh",
    category: "Formuleringer",
    find: "mvh\\.?",
    replace: "Med venlig hilsen",
    note: "I tilbud og ordrebekr\u00e6ftelser skrives hilsenen helt ud.",
    regex: true,
    matchCase: false,
    wholeWord: true,
    smartCase: false,
    enabled: true,
  },
  {
    id: "form-venlig-hilsen",
    category: "Formuleringer",
    find: "Venlig hilsen",
    replace: "Med venlig hilsen",
    note: "Ensret til \u00e9n fast afslutningshilsen. Sl\u00e5 til, hvis \u00bbMed venlig hilsen\u00ab er jeres standard.",
    regex: false,
    matchCase: true,
    wholeWord: true,
    smartCase: false,
    enabled: false,
  },
];
